// Traduções em português, usadas só para gerar page/i18n/pt-BR.po e pt-PT.po.
// Este arquivo não vai para o relógio.
export const PORTUGUES = {
  'home.preparing': 'Preparando...',
  'home.deckPrefix': 'Baralho: ',
  'home.empty': 'Nenhum baralho.\nSincronize com o celular.',
  'home.start': 'COMEÇAR',
  'home.allDone': 'Tudo em dia!',
  'home.swipe': 'deslize',
  'home.sync': 'SINCRONIZAR',
  'home.howTo': 'COMO USAR',

  'card.one': 'cartão',
  'card.many': 'cartões',

  'study.show': 'MOSTRAR',
  'study.again': 'ERREI',
  'study.hard': 'DIFÍCIL',
  'study.good': 'BOM',
  'study.easy': 'FÁCIL',

  'summary.title': 'SESSÃO CONCLUÍDA',
  'summary.hit.one': 'acerto',
  'summary.hit.many': 'acertos',
  'summary.hard.one': 'difícil',
  'summary.hard.many': 'difíceis',
  'summary.miss.one': 'erro',
  'summary.miss.many': 'erros',
  'summary.time': 'Tempo: ',
  'summary.ok': 'OK',

  'sync.title': 'SINCRONIZAR',
  'sync.connecting': 'Conectando...',
  'sync.sending': 'Enviando respostas',
  'sync.receiving': 'Recebendo cartões...',
  'sync.finishing': 'Concluindo...',
  'sync.done': 'Sincronizado!',
  'sync.failed': 'Não sincronizou',
  'sync.sent': 'Enviadas: ',
  'sync.received': 'Recebidas: ',
  'sync.ok': 'OK',
  'sync.retry': 'TENTAR',
  'sync.back': 'VOLTAR',
  'answer.one': 'resposta',
  'answer.many': 'respostas',
  'change.one': 'alteração',
  'change.many': 'alterações',

  'error.unauthorized': 'Código de pareamento inválido. Confira no Zepp App: Flashcards > Configurações.',
  'error.noServer': 'Abra o app Flashcards no celular, na aba Relógio, e tente de novo.',
  'error.protocol': 'Versões diferentes. Atualize o app do celular e o do relógio.',
  'error.pushRejected': 'O celular recusou as respostas. Tente de novo.',
  'error.badResponse': 'Resposta inválida do celular. Tente de novo.',
  'error.generic': 'Sem conexão com o celular. Verifique o Bluetooth e o Zepp App.',

  'tour.welcome.title': 'FLASHCARDS',
  'tour.welcome.text': 'Estude seus cartões no relógio, sem internet e sem levar o celular.',
  'tour.how.title': 'COMO FUNCIONA',
  'tour.how.text': '1. Crie ou importe cartões no app do celular.\n2. Toque em SINCRONIZAR.\n3. Estude aqui, offline.',
  'tour.study.title': 'ESTUDANDO',
  'tour.study.text': 'Toque em MOSTRAR e responda: ERREI, DIFÍCIL, BOM ou FÁCIL. Cada resposta define quando o cartão volta.',
  'tour.back.title': 'DE VOLTA AO CELULAR',
  'tour.back.text': 'Suas respostas ficam guardadas aqui até você sincronizar de novo. Nada se perde.',
  'tour.qr.title': 'APP DO CELULAR',
  'tour.qr.text': 'Leia o código com a câmera do celular para instalar:',
  'tour.confirm.title': 'TUDO PRONTO?',
  'tour.confirm.text': 'Você já instalou o app Flashcards no celular?',
  'tour.next': 'PRÓXIMO',
  'tour.yes': 'SIM, COMEÇAR',
  'tour.notYet': 'AINDA NÃO',

  'demo.name': 'Demonstração',
  'demo.q1': 'Para que serve este app?',
  'demo.a1': 'Estudar flashcards no relógio, offline',
  'demo.q2': 'Como os cartões chegam ao relógio?',
  'demo.a2': 'Do app do celular, tocando em SINCRONIZAR',
  'demo.q3': 'O que significa ERREI?',
  'demo.a3': 'Você esqueceu o cartão: ele volta nesta sessão',
  'demo.q4': 'O que significa FÁCIL?',
  'demo.a4': 'Não custou nada: o cartão volta bem mais tarde',
  'demo.q5': 'Precisa de internet para estudar?',
  'demo.a5': 'Não. Tudo funciona offline no relógio',
  'demo.q6': 'Para onde vão suas respostas?',
  'demo.a6': 'Ficam no relógio até a próxima sincronização',
  'demo.q7': 'O que é repetição espaçada?',
  'demo.a7': 'Revisar pouco antes de você esquecer',
  'demo.q8': 'Qual botão mostra a resposta?',
  'demo.a8': 'MOSTRAR, ou o botão de seleção do relógio',
}
